sudo: required
services:
    - docker

before_install:
    - docker build -t piyush/dockerreact -f Dockerfile.dev .

script:
    - docker run -e CI=true piyush/dockerreact npm run test


deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "dockerreact"
    env: "Dockerreact-env"
    bucket_name: "elasticbeanstalk-us-east-1-453258824039"
    bucket_path: "dockerreact"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY