version: '3'
services:
    reactapp:
        build: 
            dockerfile: Dockerfile.dev
            context: .
        volumes:
            - /app/node_modules
            -  .:/app
        ports:
            - "3000:3000"
    tests:
        build: 
            dockerfile: Dockerfile.dev
            context: .
        volumes:
            - /app/node_modules
            -  .:/app
        command: ["npm","run","test"]         